# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='picture',
            field=models.ImageField(default='/static/app/images/product4_big.jpg', upload_to=b''),
            preserve_default=False,
        ),
    ]
