# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recette_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'archivos', verbose_name=b'Imagen'),
        ),
    ]
