# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170527_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='difficulte',
            field=models.CharField(choices=[(b'F', b'Facile'), (b'M', b'Moyen'), (b'D', b'Difficile')], default=b'F', max_length=1),
        ),
    ]
