# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recette_difficulte'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='type',
            field=models.CharField(choices=[(b'E', b'Entr\xc3\xa9e'), (b'P', b'Plat'), (b'D', b'Dessert')], default=b'E', max_length=1),
        ),
    ]
