# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recette_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='connexions',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
