# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170528_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='connexions',
            new_name='connections',
        ),
    ]
