# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170528_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='connections',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
    ]
