# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170528_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='picture',
            field=models.ImageField(blank=True, default=b'/static/app/images/default.png', null=True, upload_to=b'images', verbose_name=b'Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='connections',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
