# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='picture',
            field=models.ImageField(blank=True, default=b'/static/app/images/default.png', null=True, upload_to=b'/static/app/images/', verbose_name=b'Image'),
        ),
    ]
