# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170529_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'/static/app/images/'),
        ),
    ]
