# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170602_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='picture',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 13, 23, 39, 76918)),
        ),
    ]
