# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 14:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0024_auto_20170602_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtelierInscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='atelier',
            name='restant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 14, 7, 38, 998473)),
        ),
        migrations.AddField(
            model_name='atelierinscription',
            name='atelier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Atelier'),
        ),
        migrations.AddField(
            model_name='atelierinscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
