# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20170602_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='atelierinscription',
            name='nbplace',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 14, 42, 15, 190557)),
        ),
    ]
