# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170602_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 3, 22, 55, 28, 423158)),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='place',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='restant',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
