# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20170603_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 4, 15, 42, 18, 379477)),
        ),
    ]
