# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170604_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 4, 20, 58, 31, 764495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='date',
            field=models.DateField(),
        ),
    ]
