# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20170604_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 5, 11, 32, 1, 727453)),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 5, 11, 32, 1, 727488, tzinfo=utc)),
        ),
    ]
