# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170605_0703'),
        ('app', '0030_auto_20170605_1132'),
    ]

    operations = [
    ]
