# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20170609_1936'),
        ('app', '0054_auto_20170609_1654'),
    ]

    operations = [
    ]
