# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_merge_20170609_1953'),
        ('app', '0057_auto_20170611_2211'),
    ]

    operations = [
    ]
